language: scala

scala:
  - 2.11.7

jdk:
  - oraclejdk8

before_install:
  - pip install --user codecov

script:
  - travis_retry sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success:
  - codecov
